#ifndef __ITEMDB__ITEM_VISUALS__HH__
#define __ITEMDB__ITEM_VISUALS__HH__

namespace beef
{
    enum
    {
        VISUAL_EFFECT_NORMAL,
        VISUAL_EFFECT_FLAME_LICK,
        VISUAL_EFFECT_SMOKING,
        VISUAL_EFFECT_GLOW_TINT1,
        VISUAL_EFFECT_ANIM,
        VISUAL_EFFECT_BUBBLES,
        VISUAL_EFFECT_PET,
        VISUAL_EFFECT_PET_ANIM,
        VISUAL_EFFECT_NO_ARMS,
        VISUAL_EFFECT_WAVEY,
        VISUAL_EFFECT_WAVEY_ANIM,
        VISUAL_EFFECT_BOTHARMS,
        VISUAL_EFFECT_LOWHAIR,
        VISUAL_EFFECT_UNDERFACE,
        VISUAL_EFFECT_SKINTINT,
        VISUAL_EFFECT_MASK,
        VISUAL_EFFECT_ANIM_MASK,
        VISUAL_EFFECT_LOWHAIR_MASK,
        VISUAL_EFFECT_GHOST,
        VISUAL_EFFECT_PULSE,
        VISUAL_EFFECT_COLORIZE,
        VISUAL_EFFECT_COLORIZE_TO_SHIRT,
        VISUAL_EFFECT_COLORIZE_ANIM,
        VISUAL_EFFECT_HIGHFACE,
        VISUAL_EFFECT_HIGHFACE_ANIM,
        VISUAL_EFFECT_RAINBOW_SHIFT,
        VISUAL_EFFECT_BACKFORE,
        VISUAL_EFFECT_COLORIZE_WITH_SKIN,
        VISUAL_EFFECT_NO_RENDER,
        VISUAL_EFFECT_SPIN,
        VISUAL_EFFECT_OFFHAND,
        VISUAL_EFFECT_WINGED,
        VISUAL_EFFECT_SINK,
        VISUAL_EFFECT_DARKNESS,
        VISUAL_EFFECT_LIGHTSOURCE,
        VISUAL_EFFECT_LIGHT_IF_ON,
        VISUAL_EFFECT_DISCOLOR,
        VISUAL_EFFECT_STEP_SPIN,
        VISUAL_EFFECT_PETCOLORED,
        VISUAL_EFFECT_SILKFOOT,
        VISUAL_EFFECT_TILTY,
        VISUAL_EFFECT_TILTY_DARK,
        VISUAL_EFFECT_NEXT_FRAME_IF_ON,
        VISUAL_EFFECT_WOBBLE,
        VISUAL_EFFECT_SCROLL,
        VISUAL_EFFECT_LIGHTSOURCE_PULSE,
        VISUAL_EFFECT_BUBBLE_MACHINE,
        VISUAL_EFFECT_VERYLOWHAIR,
        VISUAL_EFFECT_VERYLOWHAIR_MASK
    };
}

#endif // __ITEMDB__ITEM_VISUALS__HH__
