#ifndef __ITEMDB__ITEM_COLLISION__HH__
#define __ITEMDB__ITEM_COLLISION__HH__ 

namespace beef
{
    enum
    {
        ITEMCOLLISION_NONE,
        ITEMCOLLISION_NORMAL,
        ITEMCOLLISION_JUMP_THROUGH,
        ITEMCOLLISION_JUMP_DOWN,
        ITEMCOLLISION_GATEWAY,
        ITEMCOLLISION_IF_OFF,
        ITEMCOLLISION_IF_ON,
        ITEMCOLLISION_ONE_WAY,
        ITEMCOLLISION_VIP,
        ITEMCOLLISION_ADVENTURE,
        ITEMCOLLISION_FACTION,
        ITEMCOLLISION_GUILD,
        ITEMCOLLISION_CLOUD,
    };
}

#endif // __ITEMDB__ITEM_COLLISION__HH__
